### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by tomsux** [rwv/caj2pdf-go#2]
os:ubuntu18
go:1.18

panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/rwv/caj2pdf-go/parser/CAJParser.parseToc({0xc00010f900, 0xc00010f900?, 0x140})
	/home/sx/git/caj2pdf-go/parser/CAJParser/getToc.go:65 +0x17e
github.com/rwv/caj2pdf-go/parser/CAJParser.getToc({0x4ec760, 0xc00000e030})
	/home/sx/git/caj2pdf-go/parser/CAJParser/getToc.go:37 +0x145
github.com/rwv/caj2pdf-go/parser/CAJParser.CAJParser.Convert({{0x4ca152, 0xa}, 0x6e697354}, {0x4c9fcc, 0xa})
	/home/sx/git/caj2pdf-go/parser/CAJParser/CAJParser.go:38 +0xdc
main.main()
	/home/sx/git/caj2pdf-go/main.go:11 +0x48

**Comment by rwv** [comment]
有无文件提供？
